### ISSUE TITLE
✅Feature: HUD 업데이트

### ISSUE THREAD

**Issue by Yongsullee** [AOW-GroupProject/AgeOfWolves#105]
## #️⃣주제

> HUD 업데이트

## 📝TODO

- [ ] : 발도술 퀵슬롯 1개에 두 어빌리티 할당으로 변경
- [ ] : Horizontal Dot Gauge 의 각 Unit에 채워지기, 비워지기 시 UI Animation 추가
- [ ] : 주술 퀵슬롯 1~3번 간 회전하는 UI Animation 추가
- [ ] : 도구 1, 도구 2 퀵슬롯 인벤토리 시스템 연동 및 테스트 진행

## ⚡️개발 기한

> 24/12/2(월) ~ 24/12/5(목)

## 💬 참고 문서

> 1. x
