### ISSUE TITLE
✅Feature: 발도술 제작, Battoujutsu Gameplay Ability

### ISSUE THREAD

**Issue by Yongsullee** [AOW-GroupProject/AgeOfWolves#107]
## #️⃣주제

> 기획 내용을 토대로 발도술 1, 2, 3 제작 

## 📝TODO

- [ ] : 키 홀드 상태 시 발도 자세 유지 및 발도술 어빌리티의 Activation Required 로써 활용
- [ ] : Active GA, GA_Battoujutsu_IchiShima (발도술 1번 - 일섬, 대각 베기)  제작
- [ ] : Active GA, GA_Battoujutsu_SuiheiKiri (발도술 2번 - 수평 베기) 제작
- [ ] : Active GA, GA_Battoujutsu_SuichoukuIchiShima (발도술 3번 - 수직 베기) 제작
- [ ] : 충돌 시스템 통해 데미지 전달 테스트
- [ ] : HUD의 퀵슬롯과 연계하여 퀵슬롯 관련 사용자 입력에 대응되는 발도술 활성화 체크 및 테스트 (우선 발도술 퀵슬롯에 할당되는 발도술 어빌리티는 1개로 설정 -> 이후 2개에서 왼쪽 마우스 클릭/오른쪽 마우스 클릭으로 구분)
- [ ] : Gameplay Cue, Trail Effect(무기 궤적 보여주는 FX) 제작 및 적용
- [ ] : Gameplay Cue, Hit Effect(무기와 Target이 충돌한 지점에 충돌 여부를 시각 정보로 판단 가능한 FX) 제작 및 적용

## ⚡️개발 기한

> 24/11/27(수) ~ 24/12/05(목)

## 💬 참고 문서

> 1. 작업 진행하며 참고한 문서 여기에 링크 추가
