### ISSUE TITLE
✅Feature: Armor Gameplay Ability

### ISSUE THREAD

**Issue by Yongsullee** [AOW-GroupProject/AgeOfWolves#111]
## #️⃣주제

> 캐릭터 어빌리티 시스템에서 전달 받은 Damage Context를 처리하는 Armor Ability 제작

## 📝TODO

- [x] : Passive 유형의 GA_Armor 제작
- [x] : 전달 받은 Context 정보를 통해 Hit React 방향 결정
- [x] : 전달 받은 Context 정보를 통해 Die 결정
- [x] : 전달 받은 Context 정보를 통해 Stun 결정
- [x] : Wolf 몹 임시 스켈레톤 대체 및 피격 반응 테스트
- [x] : Wolf 관련 임시 스켈레톤, 애니메이션 추가 -> 다음 이슈에서
- [x] : 주술 1번(화구의 술) 임시 애니메이션 추가 -> 다음 이슈에서
- [x] : Dash 4방향 애니메이션 추가 -> 다음 이슈에서

## ⚡️개발 기한

> 24/12/13 ~ 24/12/23(월)
> Enemy 쪽 기반 시스템 수정 및 애셋 교체에 따른 지연

## 💬 참고 문서

> 1. x
