### ISSUE TITLE
✅Feature: Combat State Ability 제작

### ISSUE THREAD

**Issue by Yongsullee** [AOW-GroupProject/AgeOfWolves#112]
## #️⃣주제

> 캐릭터의 현재 전투/비전투 상태를 관리하는 Passive 유형의 Gameplay Ability 제작

## 📝TODO

- [x] : Application Requirement 정의, AR_IsCombatState, AR_IsNonCombatState
- [x] : Active 유형의 GA_Equip 구현
- [x] : Active 유형의 GA_Unequip 구현
- [x] : Passive 유형의 GA_CombatState 구현
- [x] : Attack 관련 GA들의 Cost에 AR_IsCombatState 추가

## ⚡️개발 기한

> 24/12/09(월) ~ 24/12/12(목)

## 💬 참고 문서

> 1. x
