### ISSUE TITLE
✅Feature: 주술 1번, GA_Jujutsu_KatonNoSuru 구현

### ISSUE THREAD

**Issue by Yongsullee** [AOW-GroupProject/AgeOfWolves#113]
## #️⃣주제

> 구현 주제에 대한 간단한 설명 및 목표

## 📝TODO

주술(Spell)
- [x] : 주술 파이어볼 기본(기획 참고, ProjectileComponent)
- [x] : GE_Cost_UseManaUnit 구현(Attribute.Mana)
- [x] : UI 연동(Mana, GE)
- [ ] : 데미지 전달 확인(UE_LOG Custom, TestActor , ASC, 미완)
- [x] : Projectile -> Linear, Homing, Curve 등으로 나눌 수 있도록 설계(기획 필)

## ⚡️개발 기한

> 24/12/13(금) ~ 24/12/19(수)

## 💬 참고 문서

> 1. x
