### ISSUE TITLE
✅Feature: Effect System, Projectile

### ISSUE THREAD

**Issue by Yongsullee** [AOW-GroupProject/AgeOfWolves#122]
## #️⃣주제

> GA의 Gameplay Cue 활용을 위한 Effect System 설계 및 Projectile 구현

## 📝TODO

- [ ] : AN_ChangeHandMaterial 구현
- [ ] : GameplayCueNotify_Actor 유형의 Gameplay Cue 제작
- [ ] : 주술 1번 GA에 위 Gameplay Cue 적용하고, 1번 작업과 2번 작업의 연동

## ⚡️개발 기한

> 날짜 입력 해주세요.

## 💬 참고 문서

> 1. 추가해주세요.

**Comment by YunTaeHo** [comment]
APlayerCharacter에서 Socket마다 AGameplayCue_Actor를 생성해서 자연스럽게 이펙트 생성할 수 있도록 설정
(AnimNotifyState 사용)

NotifyState가 Owner->PlayerCharacter를 이용해 사용할 수 있도록 설정한다

GE는 현재 Projectile이 ASC를 가지고 있어 해당 기능을 수정해야함.
