### ISSUE TITLE
✅Feature: 늑대 일반 스킬 제작

### ISSUE THREAD

**Issue by chahg0514** [AOW-GroupProject/AgeOfWolves#32]
## #️⃣주제

> 늑대 일반 스킬 10001~10007 애니메이션, 사거리, 쿨타입 등 데이터 입력할 수 있도록 구조 작성, 스킬 구현 함수 작성

## 📝TODO

- [x] : 데이터 입력 구조 작성
- [x] : 각 스킬 이동 방식 구현 함수 작성 (애니메이션만 빠진 상태로)
- [x] : Sight Config로 타겟 인식, Blackboard에 전달
- [x] : 점에서 점으로 움직일 시 자연스러운 Rotation 

## ⚡️개발 기한

> 2024/06/03 ~ 2024/06/07
> 다음 목표 날짜 : 2024/06/13
> 지연 이유: 개인 사유 + 생각보다 데이터 구조 짜는 것이 오래 걸림

> 다음 목표 날짜 : 2024/06/17
> 지연 이유: 새 이슈를 만들기엔 Conflict 발생 때문에 다음주에 할 일을 현재 이슈에 추가함
