### ISSUE TITLE
✅Feature: 몬스터 추가 작업

### ISSUE THREAD

**Issue by chahg0514** [AOW-GroupProject/AgeOfWolves#61]
## #️⃣주제

> 몬스터 추가 작업

## 📝TODO

- [x] : AI Faction
- [x] : 횡이동(포커스 유지) BT에 추가
- [ ] : 데미지 전달(ASC), 후 피격 반응 등 상호작용
- [ ] : 테스트 레벨에 더미 객체 생성
- [ ] : 회피 수정(오른쪽, 왼쪽 중에 z좌표가 크게 차이나지 않는 방향 우선?, 움직임 오류 수정)

## ⚡️개발 기한

> 2024.08.08 ~ 2024.08.22

## 💬 참고 문서

> 1. 링크_1
> 2. 문서_1
> 3. etc
