### ISSUE TITLE
✅Feature: Inventory UI 추가 기능

### ISSUE THREAD

**Issue by Yongsullee** [AOW-GroupProject/AgeOfWolves#68]
## #️⃣주제

> Inventory UI에 필요한 구성 요소들을 추가하고, 키보드 입력을 허용해주는 작업

## 📝TODO

- [x] : Item Slot의 아이템 갯수 표현, Item Count
- [x] : Item Slot 선택 시 표시할 DropDownMenu UI 설계
- [x] : Mouse Curosr 위치(화살표 끝을 상호작용의 중심으로 변경), 크기 변경

## ⚡️개발 기한

> 24/09/09(월) ~ 24/09/21(토)
> 지연되었다면, 지연 사유 및 다음 목표 날짜

## 💬 참고 문서

> 1. X
