### ISSUE TITLE
✅Feature: UI 관련 코드 리팩토링 및 UI Animation 기능 추가

### ISSUE THREAD

**Issue by Yongsullee** [AOW-GroupProject/AgeOfWolves#91]
## #️⃣주제

> UI 관련 코드 리팩토링 및 UI Animation 구현

## 📝TODO

- [ ] : UI 코드 리팩토링 진행
- [ ] : Inventory Tool Bar, Menu UI Tool Bar를 하나의 Tool Bar 유형으로 묶기
- [ ] : UI 열기/닫기 혹은 가시성 활성화/비활성화 시 Blend-In/out Animation 구현
- [ ] : Button Hover 시 Opacity 증가/감소 반복 Animation 구현

## ⚡️개발 기한

> 24/10/18(금) ~ 24/10/24(목)

## 💬 참고 문서

> X
