### ISSUE TITLE
✅Feature: HUD 새로운 디자인 적용 및 기능 업데이트

### ISSUE THREAD

**Issue by Yongsullee** [AOW-GroupProject/AgeOfWolves#95]
## #️⃣주제

> 기존 HUD를 새로운 디자인으로 업데이트 및 기능 추가

## 📝TODO

- [x] : Inventory UI 아이템 사용, 제거, 버리기 등의 기능 이후 UI 업데이트 작업
- [x] : Status UI 제작(HP, SP, MP, Memory Item)
- [x] : 주술 포인트(MP) 업데이트
- [x] : 퀵슬롯 업데이트 - 발도술(스킬 타입1), 주술(스킬 타입2), 도구 목록
- [x] : 회복 물약 UI 업데이트

## ⚡️개발 기한

> 24/10/28(월) ~ 24/11/14(목)
> 지연 사유: 개인 일정

## 💬 참고 문서

> x
